spring:
  datasource:
    username: root
    password: lvkaihe
    url: jdbc:mysql://116.62.153.32:3306/mall
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090
uploadPath: /mall_files/
mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.sr.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:/com/sr/map/*.xml
  configuration:
    jdbc-type-for-null: null
uploadFile:
  resourceHandler: /files/**   #请求 url 中的资源映射也是保存到数据库中的父级路径
